### ISSUE TITLE
UnauthorizedError: jwt issuer invalid. expected: <subomain.auth0.com>

### ISSUE THREAD

**Issue by josephkandi** [auth0-blog/react-tutorial#1]
Hello
When i follow the tutorial, i get the above error when accessing a secured url when posting a new question.

However, when i replace my credentials with yours, my code works fine. I can get the token and have checked the issuer and it matches, but somehow, the validation fails.

I have my code with these credentials and my code works fine
`domain: 'bk-tmp.auth0.com',
  audience: 'https://bk-tmp.auth0.com/userinfo',
  clientID: 'PVafIu9Q5QN65DiPByAFvCCJryY7n432',`

and these 
` audience: 'PVafIu9Q5QN65DiPByAFvCCJryY7n432',
  issuer: `https://bk-tmp.auth0.com/`,

**Comment by josephkandi** [comment]
I removed the `issuer` in the following line :
```
const checkJwt = jwt({
  secret: jwksRsa.expressJwtSecret({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: `https://my-domain/.well-known/jwks.json`
  }),
 
  // Validate the audience and the issuer.
  audience: 'client_id',
  //issuer: 'mydomain',
  algorithms: ['RS256']
});

```
then i can post without issues on a secured route.

**Comment by devdudeio** [comment]
removing the issuer is not very smart. The reason this is happening is:

if your jwksUri is: `https://my-domain/.well-known/jwks.json`
your issuer is: `my-domain/` (note the slash)

**Comment by SkepticMystic** [comment]
Thanks for your answer devdueio

**Comment by webshuriken** [comment]
@devdudeio Thank you for pointing that out.. it works.
